### Get all products
GET http://localhost:3000/api/products

### Get product by id
GET http://localhost:3000/api/products/1

### Create product
POST http://localhost:3000/api/products
Content-Type: application/json

{
  "title": "new item",
  "description": "this is a new product",
  "price": 123
}

### Update product
PUT http://localhost:3000/api/products/1
Content-Type: application/json

{
  "title": "updated item",
  "price": 200
}

### Delete product
DELETE http://localhost:3000/api/products/1

### ===== REVIEWS =====

### Get all reviews
GET http://localhost:3000/api/reviews

### Get review by id
GET http://localhost:3000/api/reviews/1

### Create review
POST http://localhost:3000/api/reviews
Content-Type: application/json

{
  "productId": 1,
  "review": "Amazing product!"
}

### Update review
PUT http://localhost:3000/api/reviews/1
Content-Type: application/json

{
  "productId": 2,
  "review": "Good quality"
}

### Delete review
DELETE http://localhost:3000/api/reviews/1
